# Generated by Django 3.2.9 on 2021-11-27 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cliente_celular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='key1',
            new_name='compra',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='key2',
            new_name='show',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
    ]
