# Generated by Django 3.2.9 on 2021-11-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211127_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='stock_entradas',
        ),
    ]
